---
title: "NABCA SoB Visualizations"
output: html_document
date: "`r sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(plotly)
library(htmlwidgets)
library(flextable)
```

```{r}
data_date <- "20221116"
```

```{r}
# Load threat name key
threats <- read_csv("/Users/ngoodby/Desktop/nabca_sob/Data/ThreatNum.csv")

countries <- c("United States", "Canada", "Mexico")

# Load and format overall threat impact data
threats_df <- data.frame()
for (i in countries){
  threats_df_add <- read_excel(sprintf("/Users/ngoodby/Desktop/nabca_sob/Data/derived/AnalysisExport_%s_%s/impact_bins_%s_%s.xlsx", 
                                 data_date, i, i, data_date), sheet=1) %>% 
    mutate(country = i)
  threats_df <- threats_df %>% bind_rows(threats_df_add)
}
threats_df$overall_impact_val <- factor(threats_df$overall_impact_val,
                                     levels = c("Negligible", "Low","Medium",
                                                "High","Very High"))

# Load and format pop size and trend data
pop_df <- data.frame()
for (i in countries){
  pop_df_add <- read_csv(sprintf("/Users/ngoodby/Desktop/nabca_sob/Data/derived/AnalysisExport_%s_%s/pop_quantiles_agg_%s_%s.csv", 
                                 data_date, i, i, data_date)) %>% 
    select(-Q1, -Q3) %>% 
    pivot_wider(names_from = question, values_from = Median) %>% 
    mutate(country = i)
  pop_df <- pop_df %>% bind_rows(pop_df_add)
}

# Load and format level 1 threat data
l1_threats <- data.frame()
for (i in countries){
  l1_add <- read_excel(sprintf("/Users/ngoodby/Desktop/nabca_sob/Data/derived/AnalysisExport_%s_%s/impact_bins_%s_%s.xlsx", 
                                 data_date, i, i, data_date), sheet=2) %>% 
    left_join(threats, by=c("level_1"="Q_group")) %>% 
    mutate(country = i)
  l1_threats <- l1_threats %>% bind_rows(l1_add) 
}
l1_threats$impact_bin <- factor(l1_threats$impact_bin,
                                       levels = c("Negligible", "Low", "Medium",
                                                  "High", "Very High"))

# Load and format continuous impact threat scores
l1_impact <- data.frame()
for (i in countries){
  l1_impact_add <- read_csv(sprintf("/Users/ngoodby/Desktop/nabca_sob/Data/derived/AnalysisExport_%s_%s/threat_quantiles_agg_%s_%s.csv", data_date, i, i, data_date)) %>% 
    separate(question, into=c('level_1','level_2'), sep="_") %>% 
    left_join(threats, by=c("level_1"="Q_group", "level_2"="Q_sub")) %>% 
    mutate(country = i)
  l1_impact <- l1_impact %>% bind_rows(l1_impact_add) 
}
```

```{r}
df <- pop_df %>% left_join(threats_df) 

pop_plot <- ggplot(data = df, aes(x=popSize, y=popTrend, color = country, 
                      shape = country, size = overall_impact_val)) +
  geom_point() +
  scale_x_log10(label = comma) 
  # scale_colour_brewer(palette = "Reds")

ggsave(here::here("visualizations", sprintf("%s_pop_plot.png", data_date)), plot=pop_plot)

pop_plotly <- ggplotly(pop_plot)

pop_plot
```

```{r}
sub_t_count <- threats %>% group_by(threat_abbrev) %>% 
  summarize(num_sub_t=n())

s <- l1_threats %>% left_join(sub_t_count)

s <- s %>% group_by(country, threat_abbrev,impact_bin, num_sub_t) %>% 
  summarize(count_instances = n()) %>% 
  # divide each l1 threat by number of l2 threats so that count of instances is standardized across l1 threats
  mutate(standardized = count_instances/num_sub_t) 
  # filter(impact_bin!="Negligible" & impact_bin!="Low")

threats_plot <- ggplot(data=s, aes(x=impact_bin, y=standardized, fill=country)) +
  geom_bar(stat='identity') +
  facet_wrap(~threat_abbrev, labeller = labeller(threat_abbrev = label_wrap_gen(15))) +
  theme(axis.text.x = element_text(angle = 90), axis.text.y = element_blank()) +
  xlab(NULL) +
  ylab(NULL)

ggsave(here::here("visualizations", sprintf("%s_l1_threats_plot.png", data_date)), plot=threats_plot)

threats_plot
```

```{r}
species_top_threats <- l1_impact %>% group_by(country, species, Threat) %>% 
  summarise(impact = sum(Median))

top_l1_threats <- species_top_threats %>% group_by(country, Threat) %>% 
  summarise(impact=sum(impact)) %>% 
  mutate(rank = rank(-impact)) %>% select(-impact) %>% 
  pivot_wider(names_from = country, values_from = rank) %>% 
  arrange(Canada, Mexico, `United States`)

ft <- flextable(top_l1_threats) %>% 
  bg(j = c(2,3,4), bg = scales::col_numeric(palette = "Reds", domain = c(1, 12), 
                                            reverse = T)) %>% 
  color(color = "white", part = "all") %>% 
  bg(bg = "black", j=1) %>% 
  bg(bg = "black", part = "header") 

ft

save_as_image(ft, "/Users/ngoodby/Downloads/threats.png", zoom = 3, expand = 10, webshot = "webshot")
```

```{r}
# Level 2 threat rankings
species_top_l2 <- l1_impact %>% group_by(country, species, Threat, subT) %>% 
  summarise(impact = sum(Median))

top_mx <- species_top_l2 %>% group_by(country, subT) %>% 
  summarise(impact=sum(impact)) %>% filter(country=="Mexico") %>% 
  arrange(desc(impact)) %>% rename(c("Mexico"="subT")) %>% ungroup() %>% 
  select(-impact, -country) 
top_us <- species_top_l2 %>% group_by(country, subT) %>% 
  summarise(impact=sum(impact)) %>% filter(country=="United States") %>% 
  arrange(desc(impact)) %>% rename(c("United States"="subT")) %>% ungroup() %>% 
  select(-impact, -country) 
top_ca <- species_top_l2 %>% group_by(country, subT) %>% 
  summarise(impact=sum(impact)) %>% filter(country=="Canada") %>% 
  arrange(desc(impact)) %>% rename(c("Canada"="subT")) %>% ungroup() %>% 
  select(-impact, -country) 
top_threat_names <- top_mx %>% bind_cols(top_us, top_ca) %>% 
  mutate(Ranking = seq(1:nrow(top_mx)), .before=1)

library(gt)
library(webshot2)

gt <- gt(top_threat_names) %>% 
  tab_header(
    title = md("**Level 2 Threat Rankings**")
  ) %>% 
  tab_options(
    column_labels.background.color = "lightcyan",
    heading.background.color = "darkcyan"
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
) %>% 
  cols_label(
    Ranking = md("**Rank**"),
    Mexico = md("**Mexico**"),
    `United States` = md("**United States**"),
    Canada = md("**Canada**")
  )
gt
gtsave(gt, "/Users/ngoodby/Downloads/threats_l2.png")
```


```{r}
# Level 1 threat rankings
top_mx <- species_top_threats %>% group_by(country, Threat) %>% 
  summarise(impact=sum(impact)) %>% filter(country=="Mexico") %>% 
  arrange(desc(impact)) %>% rename(c("Mexico"="Threat")) %>% ungroup() %>% 
  select(-impact, -country) 
top_us <- species_top_threats %>% group_by(country, Threat) %>% 
  summarise(impact=sum(impact)) %>% filter(country=="United States") %>% 
  arrange(desc(impact)) %>% rename(c("United States"="Threat")) %>% ungroup() %>% 
  select(-impact, -country) 
top_ca <- species_top_threats %>% group_by(country, Threat) %>% 
  summarise(impact=sum(impact)) %>% filter(country=="Canada") %>% 
  arrange(desc(impact)) %>% rename(c("Canada"="Threat")) %>% ungroup() %>% 
  select(-impact, -country) 
top_threat_names <- top_mx %>% bind_cols(top_us, top_ca) %>% 
  mutate(Ranking = seq(1:nrow(top_mx)), .before=1)

library(gt)
library(webshot2)

gt <- gt(top_threat_names) %>% 
  tab_header(
    title = md("**Level 1 Threat Rankings**")
  ) %>% 
  tab_options(
    column_labels.background.color = "lightcyan",
    heading.background.color = "darkcyan"
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
) %>% 
  cols_label(
    Ranking = md("**Rank**"),
    Mexico = md("**Mexico**"),
    `United States` = md("**United States**"),
    Canada = md("**Canada**")
  )
gt

gtsave(gt, "/Users/ngoodby/Downloads/threats.png")
```

```{r}
# most impacted species for each threat in each country
top_spp_per_threat <- species_top_threats %>% 
  mutate(species = str_to_sentence(species)) %>%
  mutate(species = str_replace(species, "_", " ")) %>% 
  group_by(country, species, Threat) %>% 
  summarise(impact=sum(impact)) %>% ungroup() %>% 
  group_by(country, Threat) %>% filter(impact==max(impact)) %>% 
  select(-impact) %>% 
  pivot_wider(names_from = country, values_from = species)
ft <- flextable(top_spp_per_threat) %>% 
  italic(j = 2:4, italic = TRUE, part = "body") %>% 
  autofit() %>% 
  bg(bg="white", part="all")

save_as_image(ft, "/Users/ngoodby/Downloads/top_spp.png", zoom = 3, expand = 10, webshot = "webshot")
```

```{r G Rank data}
# Load and format G Rankings
g_rank_us <- read_csv(sprintf("/Users/ngoodby/Desktop/nabca_sob/Data/derived/AnalysisExport_%s_United States/g_rankings_United States_%s.csv", data_date, data_date))
g_rank_ca <- read_csv(sprintf("/Users/ngoodby/Desktop/nabca_sob/Data/derived/AnalysisExport_%s_Canada/g_rankings_Canada_%s.csv", data_date, data_date))
g_rank_mx <- read_csv(sprintf("/Users/ngoodby/Desktop/nabca_sob/Data/derived/AnalysisExport_%s_Mexico/g_rankings_Mexico_%s.csv", data_date, data_date))

g_rank_df <- g_rank_us %>% bind_rows(g_rank_ca) %>% bind_rows(g_rank_mx)
```

```{r}
top_threat_per_spp <- species_top_threats %>% 
  group_by(country, species) %>% filter(impact==max(impact)) %>% 
  rename(c("top_threat"="Threat")) %>% select(-impact)

g_rank_df <- g_rank_df %>% left_join(top_threat_per_spp)

g_rank_bar <- ggplot(data=g_rank_df, aes(x=g_rank, fill=top_threat)) +
  geom_histogram(stat="count") +
  facet_wrap(~country) +
  xlab(NULL) +
  ylab("Count of Species") 
  # theme(legend.position="none")

g_rank_plotly <- ggplotly(g_rank_bar, tooltip='fill')

htmlwidgets::saveWidget(g_rank_plotly, 
                        sprintf("%s/visualizations/%s_g_rank.html", here::here(), data_date))
```