---
title: "Species Reports for the North American State of the Bats Assessment"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message= F, warning= F)
```

```{r}
library(tidyverse)
library(here)
dataDate <- "20221116"
```

## United States Species Reports

```{r results='asis'}
responses_dir <- paste0(here::here(), "/Data/derived/AnalysisExport_",
                         dataDate, "_United States/")
files <- list.files(responses_dir, full.names = F)
responses_file <- files[str_detect(files, 'cleaned_responses')]
responses <- read_csv(paste0(responses_dir, responses_file))

spp_df <- responses %>% select(spp, sppcode) %>% distinct() %>% dplyr::arrange(spp)

report_directory <- paste0(here::here(), "/species_reports/", dataDate, 
                           "_United States/")
report_files <- list.files(report_directory, full.names = F)
relevant_report_files <- report_files[str_detect(report_files, '.pdf')]

# to deal with the space between United and States in the file paths
report_directory <- gsub(" ", "%20", report_directory)

for (i in seq(1:nrow(spp_df))){
  spp <- spp_df$spp[i]
  sppcode <- spp_df$sppcode[i]
  f <- relevant_report_files[str_detect(relevant_report_files, sppcode)]
  # to deal with the space between United and States in the file paths
  f <- gsub(" ", "%20", f)
  cat(sprintf('[*%s*](%s%s)', spp, report_directory, f))
  cat("  \n")
}
```

## Canada Species Reports

```{r results='asis'}
responses_dir <- paste0(here::here(), "/Data/derived/AnalysisExport_",
                         dataDate, "_Canada/")
files <- list.files(responses_dir, full.names = F)
responses_file <- files[str_detect(files, 'cleaned_responses')]
responses <- read_csv(paste0(responses_dir, responses_file))

spp_df <- responses %>% select(spp, sppcode) %>% distinct() %>% dplyr::arrange(spp)

report_directory <- paste0(here::here(), "/species_reports/", dataDate, 
                           "_Canada/")
report_files <- list.files(report_directory, full.names = F)
relevant_report_files <- report_files[str_detect(report_files, '.pdf')]

for (i in seq(1:nrow(spp_df))){
  spp <- spp_df$spp[i]
  sppcode <- spp_df$sppcode[i]
  f <- relevant_report_files[str_detect(relevant_report_files, sppcode)]
  cat(sprintf('[*%s*](%s%s)', spp, report_directory, f))
  cat("  \n")
}
```

## Mexico Species Reports

```{r results='asis'}
responses_dir <- paste0(here::here(), "/Data/derived/AnalysisExport_",
                         dataDate, "_Mexico/")
files <- list.files(responses_dir, full.names = F)
responses_file <- files[str_detect(files, 'cleaned_responses')]
responses <- read_csv(paste0(responses_dir, responses_file))

spp_df <- responses %>% select(spp, sppcode) %>% distinct() %>% dplyr::arrange(spp)

report_directory <- paste0(here::here(), "/species_reports/", dataDate, 
                           "_Mexico/")
report_files <- list.files(report_directory, full.names = F)
relevant_report_files <- report_files[str_detect(report_files, '.pdf')]

for (i in seq(1:nrow(spp_df))){
  spp <- spp_df$spp[i]
  sppcode <- spp_df$sppcode[i]
  f <- relevant_report_files[str_detect(relevant_report_files, sppcode)]
  cat(sprintf('[*%s*](%s%s)', spp, report_directory, f))
  cat("  \n")
}
```

